# Generated by Django 3.0.5 on 2020-04-25 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writter',
            name='id_number',
        ),
    ]
